services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  # Mount the frontend source code
      - /app/node_modules  # Prevent overwriting node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:7000

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app  # Mount the backend source code
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mine
      - PORT=7000
      - NODE_ENV=development
      - CORS_ORIGINS=http://localhost:5173
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  default:
    driver: bridge